services:
  web:
   build:
     context: .
   restart: always
   volumes:
      - .:/var/www/html/
   ports:
      - "8001:80"

  mysql-server:
    image: mysql:8.0.19
    restart: always
    environment:
     MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql-data:/var/lib/mysql
      
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.0.1
    restart: always
    environment:
      PMA_HOST: mysql-server
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "5000:80"
volumes:
  mysql-data:
