version: "3.7"
services:
    zuril:
        build:
            context: .
        restart: always
        volumes:
            - ".:/zuril"
        env_file:
            - .env
        working_dir: "/Users/collins/Documents/Sites/php_lessons/zuriLaravel"
        command: bash -c 'php artisan migrate && php artisan serve --port=8009'
        ports:
            - "8009:8000"
        depends_on:
            - mysql-server
        links:
            - mysql-server
    mysql-server:
        image: mysql:8.0.19
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: zuri
            MYSQL_USER: root
            MYSQL_PASSWORD: root
        volumes:
            - mysql-data:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:5.0.1
        restart: always
        environment:
            PMA_HOST: mysql-server
            PMA_USER: root
            PMA_PASSWORD: root
        ports:
            - "5000:80"
volumes:
    mysql-data:
